# Generated by Django 6.0.4 on 2026-04-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutritionist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("disease_management", "Disease Management"),
                            ("sports_nutrition", "Sports Nutrition"),
                            ("general", "General Nutrition"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "credentials",
                    models.TextField(
                        blank=True,
                        help_text="Qualifications and certifications",
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="nutritionists/"
                    ),
                ),
                (
                    "availability_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to booking calendar (Calendly, etc.)",
                        null=True,
                    ),
                ),
                (
                    "zoom_meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Default Zoom meeting link for consultations",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nutritionist",
                "verbose_name_plural": "Nutritionists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="When the consultation is scheduled"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (60, "60 minutes"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "zoom_link",
                    models.URLField(
                        blank=True,
                        help_text="Zoom meeting link for the consultation",
                        null=True,
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        blank=True,
                        help_text="Topics to discuss during consultation",
                        null=True,
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a premium consultation",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Consultation notes (filled after meeting)",
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommendations from nutritionist",
                        null=True,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the consultation was completed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nutritionist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="consultations.nutritionist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Feedback",
                "verbose_name_plural": "Consultation Feedbacks",
            },
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["user", "scheduled_at"], name="consultatio_user_id_721d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(fields=["status"], name="consultatio_status_787364_idx"),
        ),
    ]
