# Generated by Django 6.0.4 on 2026-04-21 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="post_notes",
            field=models.TextField(
                blank=True, help_text="Nutritionist notes after session", null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="session_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly_checkin", "Monthly Check-In"),
                    ("diet_plan_review", "Diet Plan Review"),
                    ("initial_assessment", "Initial Assessment"),
                    ("progress_review", "Progress Review"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="duration_minutes",
            field=models.IntegerField(
                choices=[(15, "15 min"), (30, "30 min"), (60, "60 min")], default=30
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="notes",
            field=models.TextField(
                blank=True, help_text="User notes before the session", null=True
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="topic",
            field=models.TextField(
                blank=True, help_text="Main topic for the session", null=True
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="zoom_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultationfeedback",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 – Poor"),
                    (2, "2 – Fair"),
                    (3, "3 – Good"),
                    (4, "4 – Very Good"),
                    (5, "5 – Excellent"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="nutritionist",
            name="availability_url",
            field=models.URLField(
                blank=True, help_text="Calendly link etc.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nutritionist",
            name="zoom_meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NutritionistFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Nutritionist's notes/feedback visible to the patient"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritionist_feedback",
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutritionist Feedback",
                "verbose_name_plural": "Nutritionist Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
