# Generated by Django 6.0.4 on 2026-04-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_moderation_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="blog",
            new_name="blogs_blog_moderat_53e41c_idx",
            old_name="blogs_blog_moderat_2950cf_idx",
        ),
    ]
