# Generated by Django 4.2.11 on 2026-04-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blogs",
            "0003_rename_blogs_blog_moderat_2950cf_idx_blogs_blog_moderat_53e41c_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Lifestyle & Occasions", "Lifestyle & Occasions"),
                    ("For Health Conditions", "For Health Conditions"),
                ],
                default="Lifestyle & Occasions",
                help_text="Category of the blog post",
                max_length=100,
            ),
        ),
    ]
