# Generated by Django 4.2.11 on 2026-04-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
    ]
