from django.urls import path

from .views import (
    AdminContentApproveView,
    AdminContentRejectView,
    AdminContentView,
    AdminLoginView,
    AdminMeView,
    AdminNutritionistDetailView,
    AdminNutritionistsView,
    AdminNutritionistStatusView,
    AdminPasswordView,
    AdminProfileView,
    AdminRevenueStatsView,
    AdminStatsView,
    AdminSubscriptionCancelView,
    AdminSubscriptionsView,
    AdminAssignableUsersView,
    AdminAssignUserToNutritionistView,
    AdminTestimonialApproveView,
    AdminTestimonialFeatureView,
    AdminTestimonialRejectView,
    AdminTestimonialsView,
    AdminTicketAssignView,
    AdminTicketReplyView,
    AdminTicketsView,
    AdminTicketStatusView,
    AdminTransactionRefundView,
    AdminTransactionsView,
    AdminUserBanView,
    AdminUserDetailView,
    AdminUsersView,
)

urlpatterns = [
    path("login", AdminLoginView.as_view()),
    path("me", AdminMeView.as_view()),
    path("profile", AdminProfileView.as_view()),
    path("password", AdminPasswordView.as_view()),
    path("stats", AdminStatsView.as_view()),
    path("users", AdminUsersView.as_view()),
    path("users/<int:user_id>", AdminUserDetailView.as_view()),
    path("users/<int:user_id>/ban", AdminUserBanView.as_view()),
    path("nutritionists", AdminNutritionistsView.as_view()),
    path("nutritionists/<int:nutritionist_id>", AdminNutritionistDetailView.as_view()),
    path("nutritionists/<int:nutritionist_id>/status", AdminNutritionistStatusView.as_view()),
    path("nutritionists/<int:nutritionist_id>/assign-user", AdminAssignUserToNutritionistView.as_view()),
    path("assignable-users", AdminAssignableUsersView.as_view()),
    path("subscriptions", AdminSubscriptionsView.as_view()),
    path("subscriptions/<int:subscription_id>/cancel", AdminSubscriptionCancelView.as_view()),
    path("content", AdminContentView.as_view()),
    path("content/<int:content_id>/approve", AdminContentApproveView.as_view()),
    path("content/<int:content_id>/reject", AdminContentRejectView.as_view()),
    path("tickets", AdminTicketsView.as_view()),
    path("tickets/<int:ticket_id>/status", AdminTicketStatusView.as_view()),
    path("tickets/<int:ticket_id>/assign", AdminTicketAssignView.as_view()),
    path("tickets/<int:ticket_id>/reply", AdminTicketReplyView.as_view()),
    path("revenue/stats", AdminRevenueStatsView.as_view()),
    path("transactions", AdminTransactionsView.as_view()),
    path("transactions/<uuid:transaction_id>/refund", AdminTransactionRefundView.as_view()),
    path("testimonials", AdminTestimonialsView.as_view()),
    path("testimonials/<int:testimonial_id>/approve", AdminTestimonialApproveView.as_view()),
    path("testimonials/<int:testimonial_id>/reject", AdminTestimonialRejectView.as_view()),
    path("testimonials/<int:testimonial_id>/feature", AdminTestimonialFeatureView.as_view()),
]
