from django.urls import path

from .views import (
    AdminContentApproveView,
    AdminContentRejectView,
    AdminContentView,
    AdminDietPlanApproveView,
    AdminDietPlanRejectView,
    AdminDietPlansView,
    AdminLoginView,
    AdminMeView,
    AdminNutritionistDetailView,
    AdminNutritionistsView,
    AdminNutritionistStatusView,
    AdminPasswordView,
    AdminProfileView,
    AdminRevenueStatsView,
    AdminRevenueSubscribersView,
    AdminRevenueSummaryView,
    AdminRevenueTrendView,
    AdminStatsView,
    AdminSubscriptionCancelView,
    AdminSubscriptionPlanDetailView,
    AdminSubscriptionPlansView,
    AdminSubscriptionsView,
    AdminTestimonialApproveView,
    AdminTestimonialFeatureView,
    AdminTestimonialRejectView,
    AdminTestimonialsView,
    AdminTicketAssignView,
    AdminTicketReplyView,
    AdminTicketsView,
    AdminTicketStatusView,
    AdminNotificationReadView,
    AdminNotificationsMarkAllReadView,
    AdminNotificationsView,
    AdminTransactionRefundView,
    AdminTransactionsView,
    AdminUserBanView,
    AdminUserDetailView,
    AdminUsersView,
)

urlpatterns = [
    path("login", AdminLoginView.as_view()),
    path("me", AdminMeView.as_view()),
    path("profile", AdminProfileView.as_view()),
    path("password", AdminPasswordView.as_view()),
    path("stats", AdminStatsView.as_view()),
    path("users", AdminUsersView.as_view()),
    path("users/<int:user_id>", AdminUserDetailView.as_view()),
    path("users/<int:user_id>/ban", AdminUserBanView.as_view()),
    path("nutritionists", AdminNutritionistsView.as_view()),
    path("nutritionists/<int:nutritionist_id>", AdminNutritionistDetailView.as_view()),
    path("nutritionists/<int:nutritionist_id>/status", AdminNutritionistStatusView.as_view()),
    path("subscriptions", AdminSubscriptionsView.as_view()),
    path("subscriptions/<int:subscription_id>/cancel", AdminSubscriptionCancelView.as_view()),
    path("subscription-plans", AdminSubscriptionPlansView.as_view()),
    path("subscription-plans/<int:plan_id>", AdminSubscriptionPlanDetailView.as_view()),
    path("content", AdminContentView.as_view()),
    # content_id is a compound id (e.g. "blog_12", "diet_7")
    path("content/<str:content_id>/approve", AdminContentApproveView.as_view()),
    path("content/<str:content_id>/reject", AdminContentRejectView.as_view()),
    path("diet-plans", AdminDietPlansView.as_view()),
    path("diet-plans/<int:template_id>/approve", AdminDietPlanApproveView.as_view()),
    path("diet-plans/<int:template_id>/reject", AdminDietPlanRejectView.as_view()),
    path("tickets", AdminTicketsView.as_view()),
    path("tickets/<int:ticket_id>/status", AdminTicketStatusView.as_view()),
    path("tickets/<int:ticket_id>/assign", AdminTicketAssignView.as_view()),
    path("tickets/<int:ticket_id>/reply", AdminTicketReplyView.as_view()),
    path("notifications", AdminNotificationsView.as_view()),
    path("notifications/mark-all-read", AdminNotificationsMarkAllReadView.as_view()),
    path("notifications/<int:notification_id>/read", AdminNotificationReadView.as_view()),
    path("revenue/stats", AdminRevenueStatsView.as_view()),
    path("revenue/summary", AdminRevenueSummaryView.as_view()),
    path("revenue/trend", AdminRevenueTrendView.as_view()),
    path("revenue/subscribers", AdminRevenueSubscribersView.as_view()),
    path("transactions", AdminTransactionsView.as_view()),
    path("transactions/<uuid:transaction_id>/refund", AdminTransactionRefundView.as_view()),
    path("testimonials", AdminTestimonialsView.as_view()),
    path("testimonials/<int:testimonial_id>/approve", AdminTestimonialApproveView.as_view()),
    path("testimonials/<int:testimonial_id>/reject", AdminTestimonialRejectView.as_view()),
    path("testimonials/<int:testimonial_id>/feature", AdminTestimonialFeatureView.as_view()),
]
