# Generated by Django 6.0.4 on 2026-04-19 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "calories_per_100g",
                    models.FloatField(help_text="Calories per 100 grams"),
                ),
                (
                    "protein_per_100g",
                    models.FloatField(default=0, help_text="Protein in grams per 100g"),
                ),
                (
                    "carbs_per_100g",
                    models.FloatField(
                        default=0, help_text="Carbohydrates in grams per 100g"
                    ),
                ),
                (
                    "fat_per_100g",
                    models.FloatField(default=0, help_text="Fat in grams per 100g"),
                ),
                (
                    "fiber_per_100g",
                    models.FloatField(default=0, help_text="Fiber in grams per 100g"),
                ),
                (
                    "category",
                    models.CharField(
                        default="other",
                        help_text="e.g., vegetable, fruit, protein, grain, dairy",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="food_items/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food Item",
                "verbose_name_plural": "Food Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "meal_image",
                    models.ImageField(
                        help_text="Original image uploaded by user",
                        upload_to="meal_images/",
                    ),
                ),
                (
                    "total_calories",
                    models.FloatField(
                        default=0, help_text="Total calories estimated by AI"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence score from AI model (0-1)"
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the meal was actually consumed",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about the meal", null=True
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether user edited AI predictions"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
                "ordering": ["-consumed_at"],
            },
        ),
        migrations.CreateModel(
            name="MealFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField(help_text="Quantity of the food item")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Grams"),
                            ("ml", "Milliliters"),
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                            ("piece", "Piece"),
                            ("slice", "Slice"),
                            ("bowl", "Bowl"),
                        ],
                        default="g",
                        max_length=20,
                    ),
                ),
                (
                    "calories",
                    models.FloatField(help_text="Calculated calories for this portion"),
                ),
                ("protein_g", models.FloatField(default=0)),
                ("carbs_g", models.FloatField(default=0)),
                ("fat_g", models.FloatField(default=0)),
                ("fiber_g", models.FloatField(default=0)),
                (
                    "ai_detected",
                    models.BooleanField(
                        default=True,
                        help_text="Whether AI detected this item (vs user-added)",
                    ),
                ),
                (
                    "user_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user manually edited this item",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="AI confidence for this specific item"
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_instances",
                        to="meals.fooditem",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Food Item",
                "verbose_name_plural": "Meal Food Items",
                "ordering": ["meal"],
            },
        ),
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_calories", models.FloatField(default=0)),
                ("total_protein_g", models.FloatField(default=0)),
                ("total_carbs_g", models.FloatField(default=0)),
                ("total_fat_g", models.FloatField(default=0)),
                ("total_fiber_g", models.FloatField(default=0)),
                ("meal_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under", "Under Goal"),
                            ("within", "Within Goal"),
                            ("over", "Over Goal"),
                        ],
                        default="within",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Nutrition Summary",
                "verbose_name_plural": "Daily Nutrition Summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="meals_daily_user_id_b64491_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "consumed_at"], name="meals_meal_user_id_70c6ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["consumed_at"], name="meals_meal_consume_ba577a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealfooditem",
            unique_together={("meal", "food_item")},
        ),
    ]
