# Generated by Django 6.0.4 on 2026-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_alter_dailynutritionsummary_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Snack", "Snack"),
                    ("Dinner", "Dinner"),
                ],
                default="Breakfast",
                help_text="Type of meal (Breakfast, Lunch, Snack, Dinner)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
