# Generated by Django 6.0.4 on 2026-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_meal_consumed_at_meal_meal_type_meal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="calories_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="carbs_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="category",
            field=models.CharField(default="other", max_length=50),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="fat_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="fiber_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="protein_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="ai_confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meal",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="ai_detected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="calories",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="carbs_g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="fat_g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="fiber_g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="protein_g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="unit",
            field=models.CharField(default="g", max_length=20),
        ),
        migrations.AddField(
            model_name="mealfooditem",
            name="user_edited",
            field=models.BooleanField(default=False),
        ),
    ]
