# Generated by Django 6.0.4 on 2026-04-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0004_adminnotification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminnotification",
            new_name="adminpanel__recipie_aaf7ef_idx",
            old_name="adminpanel__recipie_6f71c5_idx",
        ),
        migrations.RenameIndex(
            model_name="adminnotification",
            new_name="adminpanel__is_read_3a9dde_idx",
            old_name="adminpanel__is_read_6f2368_idx",
        ),
    ]
