# Generated by Django 6.0.4 on 2026-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpanel",
            "0005_rename_adminpanel__recipie_6f71c5_idx_adminpanel__recipie_aaf7ef_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
