# Generated by Django 6.0.4 on 2026-04-20 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_calorie_goal",
                    models.FloatField(
                        default=2000, help_text="Daily calorie target in kcal"
                    ),
                ),
                (
                    "protein_goal_g",
                    models.FloatField(
                        default=120, help_text="Daily protein target in grams"
                    ),
                ),
                (
                    "carbs_goal_g",
                    models.FloatField(
                        default=200, help_text="Daily carbohydrate target in grams"
                    ),
                ),
                (
                    "fat_goal_g",
                    models.FloatField(
                        default=65, help_text="Daily fat target in grams"
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True, help_text="Height in centimetres", null=True
                    ),
                ),
                (
                    "start_weight_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Weight when the user first signed up",
                        null=True,
                    ),
                ),
                (
                    "current_weight_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Most recent logged weight (kept in sync by WeightEntry signal)",
                        null=True,
                    ),
                ),
                (
                    "goal_weight_kg",
                    models.FloatField(blank=True, help_text="Target weight", null=True),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has an active premium subscription",
                    ),
                ),
                (
                    "subscription_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current subscription period ends",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the measurements were taken",
                    ),
                ),
                ("waist_cm", models.FloatField(blank=True, null=True)),
                ("hips_cm", models.FloatField(blank=True, null=True)),
                ("chest_cm", models.FloatField(blank=True, null=True)),
                ("arms_cm", models.FloatField(blank=True, null=True)),
                ("neck_cm", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Measurement",
                "verbose_name_plural": "Body Measurements",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="profiles_bo_user_id_9a8366_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of the weigh-in",
                    ),
                ),
                ("weight_kg", models.FloatField(help_text="Weight in kilograms")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional note (e.g. 'after workout')"
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight Entry",
                "verbose_name_plural": "Weight Entries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="profiles_we_user_id_1990ce_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
