# Generated by Django 6.0.4 on 2026-04-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="carbs_goal_g",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="daily_calorie_goal",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="fat_goal_g",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="protein_goal_g",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("premium", "Premium")],
                help_text="Which plan the user subscribed to",
                max_length=20,
                null=True,
            ),
        ),
    ]
