# Generated by Django 6.0.4 on 2026-04-21 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_userprofile_carbs_goal_g_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="carbs_goal_g",
            field=models.FloatField(
                blank=True, help_text="Daily carbohydrate target in grams", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_calorie_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily calorie target in kcal", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fat_goal_g",
            field=models.FloatField(
                blank=True, help_text="Daily fat target in grams", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goal_setting_mode",
            field=models.CharField(
                choices=[("auto", "AUTO"), ("manual", "MANUAL")],
                default="auto",
                help_text="Whether goals are auto-calculated or manually set by nutritionist",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Nutritionist who manages this user's goals",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="protein_goal_g",
            field=models.FloatField(
                blank=True, help_text="Daily protein target in grams", null=True
            ),
        ),
    ]
