# Generated by Django 6.0.4 on 2026-04-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userprofile_carbs_goal_g_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionistFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the feedback", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Detailed feedback message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has read this feedback",
                    ),
                ),
                (
                    "nutritionist",
                    models.ForeignKey(
                        help_text="Nutritionist sending the feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving the feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutritionist Feedback",
                "verbose_name_plural": "Nutritionist Feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="profiles_nu_user_id_6d83aa_idx",
                    ),
                    models.Index(
                        fields=["nutritionist", "-created_at"],
                        name="profiles_nu_nutriti_569464_idx",
                    ),
                ],
            },
        ),
    ]
