# Generated by Django 6.0.4 on 2026-04-23 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_nutritionistfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodymeasurement",
            options={
                "ordering": ["-date", "-logged_at"],
                "verbose_name_plural": "Body Measurements",
            },
        ),
        migrations.AlterModelOptions(
            name="weightentry",
            options={"ordering": ["-date", "-logged_at"]},
        ),
        migrations.RemoveIndex(
            model_name="bodymeasurement",
            name="profiles_bo_user_id_9a8366_idx",
        ),
        migrations.RemoveIndex(
            model_name="weightentry",
            name="profiles_we_user_id_1990ce_idx",
        ),
        migrations.AlterUniqueTogether(
            name="bodymeasurement",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="subscription_expires_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="carbs_goal_g",
            field=models.FloatField(blank=True, default=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="daily_calorie_goal",
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="fat_goal_g",
            field=models.FloatField(blank=True, default=65, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal_setting_mode",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal_weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height_cm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managing_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="protein_goal_g",
            field=models.FloatField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="start_weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium"), ("pro", "Pro")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="weightentry",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="weightentry",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="weightentry",
            name="weight_kg",
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name="bodymeasurement",
            index=models.Index(
                fields=["user", "-date"], name="profiles_bo_user_id_d4a816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weightentry",
            index=models.Index(
                fields=["user", "-date"], name="profiles_we_user_id_99e8e4_idx"
            ),
        ),
    ]
