# Generated by Django 6.0.4 on 2026-04-24 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_bodymeasurement_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the diet plan (e.g., 'Standard Plan', 'Keto Plan')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the plan"
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Plan"),
                            ("seasonal", "Seasonal Plan"),
                            ("ramadan", "Ramadan Plan"),
                            ("medical", "Medical Plan"),
                            ("custom", "Custom Plan"),
                        ],
                        default="standard",
                        help_text="Type/category of the plan",
                        max_length=20,
                    ),
                ),
                (
                    "daily_calorie_target",
                    models.IntegerField(
                        blank=True,
                        help_text="Target daily calories for this plan",
                        null=True,
                    ),
                ),
                (
                    "protein_target_g",
                    models.FloatField(
                        blank=True, help_text="Target protein in grams", null=True
                    ),
                ),
                (
                    "carbs_target_g",
                    models.FloatField(
                        blank=True, help_text="Target carbs in grams", null=True
                    ),
                ),
                (
                    "fat_target_g",
                    models.FloatField(
                        blank=True, help_text="Target fat in grams", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the currently active plan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nutritionist who assigned the plan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Patient the plan is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diet Plan",
                "verbose_name_plural": "Diet Plans",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="profiles_di_user_id_1b77b9_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="profiles_di_user_id_535082_idx",
                    ),
                ],
            },
        ),
    ]
