# Generated by Django 6.0.4 on 2026-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_dietplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="meals_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Structured daily meal plan data"
            ),
        ),
    ]
