# Generated by Django 6.0.4 on 2026-04-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_userprofile_activity_level_userprofile_allergies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="activity_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="body_fat",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="diet_style",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="goal_desc",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="goal_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="medical_conditions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="medications",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="sleep_target_hours",
        ),
    ]
