# Generated by Django 4.2.11 on 2026-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_remove_userprofile_activity_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro")],
                default="free",
                max_length=20,
            ),
        ),
    ]
