# Generated by Django 6.0.4 on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_diet_plan_templates(apps, schema_editor):
    DietPlanTemplate = apps.get_model("profiles", "DietPlanTemplate")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split(".", 1))

    # Mirror of src/data/mockData.js -> dietPlans
    mock = [
        {"id": "plan_001", "name": "Laila — Low Carb Phase 2", "kcal": 1800, "type": "Standard"},
        {"id": "plan_002", "name": "Standard Weight Loss", "kcal": 1600, "type": "Standard"},
        {"id": "plan_003", "name": "Mediterranean", "kcal": 2000, "type": "Seasonal"},
        {"id": "plan_004", "name": "Diabetic-Friendly", "kcal": 1700, "type": "Medical"},
        {"id": "plan_005", "name": "Ramadan Special", "kcal": 1900, "type": "Ramadan"},
        {"id": "plan_006", "name": "High Protein", "kcal": 2200, "type": "Standard"},
    ]

    type_map = {
        "standard": "standard",
        "seasonal": "seasonal",
        "ramadan": "ramadan",
        "medical": "medical",
        "custom": "custom",
    }

    nutritionist = User.objects.filter(is_nutritionist=True).order_by("id").first()

    for row in mock:
        title = row.get("name") or "Diet Plan"
        kcal = row.get("kcal")
        raw_type = str(row.get("type") or "standard").strip().lower()
        plan_type = type_map.get(raw_type, "standard")

        # Keep idempotent: match by title + kcal + plan_type.
        exists = DietPlanTemplate.objects.filter(
            title=title,
            daily_calorie_target=kcal,
            plan_type=plan_type,
        ).exists()
        if exists:
            continue

        DietPlanTemplate.objects.create(
            created_by=nutritionist,  # may be None => system template
            title=title,
            description="",
            plan_type=plan_type,
            daily_calorie_target=kcal,
            protein_target_g=None,
            carbs_target_g=None,
            fat_target_g=None,
            meals_data={},
            is_published=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_userprofile_subscription_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlanTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Plan"),
                            ("seasonal", "Seasonal Plan"),
                            ("ramadan", "Ramadan Plan"),
                            ("medical", "Medical Plan"),
                            ("custom", "Custom Plan"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("daily_calorie_target", models.IntegerField(blank=True, null=True)),
                ("protein_target_g", models.FloatField(blank=True, null=True)),
                ("carbs_target_g", models.FloatField(blank=True, null=True)),
                ("fat_target_g", models.FloatField(blank=True, null=True)),
                ("meals_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the template is visible in the nutritionist library",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nutritionist who created the template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_plan_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diet Plan Template",
                "verbose_name_plural": "Diet Plan Templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dietplantemplate",
            index=models.Index(fields=["created_by", "-created_at"], name="profiles_di_created_8f24d5_idx"),
        ),
        migrations.AddIndex(
            model_name="dietplantemplate",
            index=models.Index(fields=["plan_type", "-created_at"], name="profiles_di_plan_ty_7f4a1f_idx"),
        ),
        migrations.RunPython(seed_diet_plan_templates, migrations.RunPython.noop),
    ]

