# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models


def backfill_template_status(apps, schema_editor):
    DietPlanTemplate = apps.get_model("profiles", "DietPlanTemplate")
    # Anything already published becomes approved.
    DietPlanTemplate.objects.filter(is_published=True).update(moderation_status="Approved")
    # Anything not published becomes pending.
    DietPlanTemplate.objects.filter(is_published=False).update(moderation_status="Pending")


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_dietplantemplate_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplantemplate",
            name="moderation_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")],
                default="Pending",
                help_text="Admin moderation state for public listing.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dietplantemplate",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the template is visible in the public catalog (admin-controlled).",
            ),
        ),
        migrations.RunPython(backfill_template_status, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="dietplantemplate",
            index=models.Index(
                fields=["moderation_status", "-created_at"],
                name="profiles_di_moderat_6b0e3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dietplantemplate",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="profiles_di_is_pu_2dd0ff_idx",
            ),
        ),
    ]

