# Generated by Cursor on 2026-04-29

from django.db import migrations, models
from django.db.models import F


def backfill_overview(apps, schema_editor):
    DietPlanTemplate = apps.get_model("profiles", "DietPlanTemplate")
    # Best-effort: for older templates, treat description as overview if overview is empty.
    DietPlanTemplate.objects.filter(overview="").update(overview=F("description"))


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_dietplantemplate_moderation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplantemplate",
            name="overview",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Long-form overview shown on the public diet plan detail page.",
            ),
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="key_guidelines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of key guideline strings shown on the public detail page.",
            ),
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="example_meals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of example meal strings shown on the public detail page.",
            ),
        ),
        migrations.RunPython(backfill_overview, migrations.RunPython.noop),
    ]

