# Generated by Django 4.2.11 on 2026-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_dietplantemplate_sections"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dietplantemplate",
            new_name="profiles_di_created_eb6f3c_idx",
            old_name="profiles_di_created_8f24d5_idx",
        ),
        migrations.RenameIndex(
            model_name="dietplantemplate",
            new_name="profiles_di_plan_ty_332fa3_idx",
            old_name="profiles_di_plan_ty_7f4a1f_idx",
        ),
        migrations.RenameIndex(
            model_name="dietplantemplate",
            new_name="profiles_di_moderat_d12017_idx",
            old_name="profiles_di_moderat_6b0e3d_idx",
        ),
        migrations.RenameIndex(
            model_name="dietplantemplate",
            new_name="profiles_di_is_publ_f213fd_idx",
            old_name="profiles_di_is_pu_2dd0ff_idx",
        ),
        migrations.AddField(
            model_name="dietplantemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("For Lifestyle & Occasions", "For Lifestyle & Occasions"),
                    ("For Health Conditions", "For Health Conditions"),
                ],
                default="For Lifestyle & Occasions",
                help_text="Category of the diet plan",
                max_length=100,
            ),
        ),
    ]
