# Generated by Cursor on 2026-04-29

from django.db import migrations


def delete_all_templates(apps, schema_editor):
    DietPlanTemplate = apps.get_model("profiles", "DietPlanTemplate")
    DietPlanTemplate.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_rename_profiles_di_created_8f24d5_idx_profiles_di_created_eb6f3c_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_all_templates, migrations.RunPython.noop),
    ]

