# Generated by Django 4.2.11 on 2026-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_delete_all_diet_plan_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietplantemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("Lifestyle & Occasions", "Lifestyle & Occasions"),
                    ("For Health Conditions", "For Health Conditions"),
                ],
                default="Lifestyle & Occasions",
                help_text="Category of the diet plan",
                max_length=100,
            ),
        ),
    ]
