# Generated by Django 4.2.11 on 2026-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_alter_dietplantemplate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplantemplate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image file",
                null=True,
                upload_to="diet_plans/",
            ),
        ),
    ]
