# Generated by Django 6.0.4 on 2026-04-19 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="start_weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight at the time of onboarding (never updated after that)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Current weight in kilograms",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
