# Generated by Django 6.0.4 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_start_weight_alter_customuser_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_nutritionist",
            field=models.BooleanField(
                default=False, help_text="Can access nutritionist panel"
            ),
        ),
    ]
