# Generated by Django 6.0.4 on 2026-04-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_nutritionist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="activity_level",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="body_fat",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="daily_calorie_goal",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="diet_style",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="goal_desc",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="goal_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="goal_weight",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="height",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="location",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="medical_conditions",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="medications",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sleep_target_hours",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="start_weight",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="weight",
        ),
    ]
