# Generated by Django 6.0.4 on 2026-04-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_activity_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activity_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="allergies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="body_fat",
            field=models.FloatField(
                blank=True, help_text="Body fat percentage", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="daily_calorie_goal",
            field=models.IntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(800),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="diet_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="goal",
            field=models.CharField(
                choices=[
                    ("lose", "Lose Weight"),
                    ("maintain", "Maintain Weight"),
                    ("gain", "Gain Weight"),
                ],
                default="maintain",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="goal_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="goal_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="goal_weight",
            field=models.FloatField(
                blank=True, help_text="Target weight in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Height in centimeters",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="medical_conditions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="medications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sleep_target_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="start_weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight at the time of onboarding (never updated after that)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Current weight in kilograms",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
