# Generated by Django 6.0.4 on 2026-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_plan_customuser_plan_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
